tap "buo/cask-upgrade"
tap "caskroom/cask"
tap "caskroom/fonts"
tap "eugenmayer/dockersync"
tap "fnichol/dvm"
tap "homebrew/apache"
tap "homebrew/binary"
tap "homebrew/boneyard"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/dupes"
tap "homebrew/games"
tap "homebrew/headonly"
tap "homebrew/php"
tap "homebrew/python"
tap "homebrew/services"
tap "homebrew/versions"
tap "homebrew/x11"
tap "monochromegane/pt"
tap "mopidy/mopidy"
tap "mpv-player/mpv"
tap "neomutt/neomutt"
tap "neovim/neovim"
tap "osx-cross/avr"
tap "universal-ctags/universal-ctags"
brew "ack"
brew "aiccu"
brew "aircrack-ng"
brew "libyaml"
brew "gdbm"
brew "python"
brew "ansible"
brew "ant"
brew "ant-contrib"
brew "apple-gcc42"
brew "apr"
brew "apr-util"
brew "aria2"
brew "libnet"
brew "arping"
brew "docbook"
brew "asciidoc", args: ["with-docbook-xsl"]
brew "clasp"
brew "gringo"
brew "aspcud"
brew "aspell", args: ["with-lang-de", "with-lang-en"]
brew "freetype"
brew "fontconfig"
brew "gettext"
brew "glib"
brew "pixman"
brew "cairo"
brew "git"
brew "atk"
brew "atool"
brew "autoconf"
brew "automake"
brew "libelf"
brew "libusb"
brew "libusb-compat"
brew "libftdi0"
brew "avrdude"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "bchunk"
brew "bdw-gc"
brew "bison"
brew "bltool"
brew "boost", args: ["with-icu4c"]
brew "python3"
brew "burl"
brew "ghc"
brew "cabal-install"
brew "ocaml"
brew "ocamlbuild"
brew "camlp4"
brew "cataclysm"
brew "ccd2iso"
brew "cloc"
brew "cmake"
brew "cmatrix"
brew "contacts"
brew "coreutils"
brew "cscope"
brew "ctags"
brew "zeromq"
brew "czmq"
brew "dbus"
brew "dfu-programmer"
brew "diff-so-fancy"
brew "libgpg-error"
brew "libassuan"
brew "libgcrypt"
brew "libksba"
brew "pth"
brew "dirmngr"
brew "dnsmasq", restart_service: true
brew "docbook-xsl"
brew "docutils"
brew "dos2unix"
brew "duck"
brew "editorconfig"
brew "jpeg"
brew "wxmac"
brew "erlang"
brew "faac"
brew "faad2"
brew "fasd"
brew "fcgi"
brew "fdupes"
brew "giflib"
brew "imlib2"
brew "libexif"
brew "feh"
brew "lame"
brew "libogg"
brew "x264"
brew "xvid"
brew "ffmpeg", args: ["with-libvpx", "with-opus", "with-rtmpdump", "with-theora", "with-x265"]
brew "findutils"
brew "pcre2"
brew "fish"
brew "flac", args: ["with-libogg"]
brew "fluid-synth"
brew "icu4c"
brew "harfbuzz"
brew "libtool"
brew "pango"
brew "fontforge"
brew "fribidi"
brew "fswatch"
brew "fzf"
brew "gmp"
brew "isl"
brew "mpfr"
brew "libmpc"
brew "gcc"
brew "gd"
brew "shared-mime-info"
brew "gdk-pixbuf"
brew "gifsicle"
brew "git-cal"
brew "git-game"
brew "glew"
brew "libtasn1"
brew "libunistring"
brew "nettle"
brew "gsettings-desktop-schemas"
brew "glib-networking"
brew "glm"
brew "global", args: ["with-ctags", "with-pygments"]
brew "gmime"
brew "libxml2", args: ["with-python"]
brew "gnome-doc-utils"
brew "pinentry"
brew "gnupg"
brew "lua"
brew "gnuplot"
brew "sdl2"
brew "sdl2_image"
brew "gource"
brew "gpg-agent"
brew "graphviz"
brew "grc"
brew "orc"
brew "gst-plugins-bad", args: ["with-faad2", "with-libmms", "with-opus"]
brew "gstreamer@0.10"
brew "gst-plugins-base@0.10", args: ["with-libogg", "with-libvorbis", "with-theora"]
brew "libmms"
brew "libsndfile"
brew "gst-plugins-bad@0.10"
brew "vala"
brew "libsoup"
brew "theora"
brew "gst-plugins-good", args: ["with-flac", "with-libshout", "with-speex", "with-taglib"]
brew "gst-plugins-good@0.10", args: ["with-flac", "with-jpeg", "with-libshout", "with-libsoup", "with-speex", "with-taglib"]
brew "gst-plugins-ugly", args: ["with-flac", "with-lame", "with-libmms", "with-libshout", "with-libvorbis", "with-mad", "with-theora", "with-two-lame"]
brew "gst-plugins-ugly@0.10", args: ["with-flac", "with-lame", "with-libmms", "with-libvorbis", "with-mad", "with-theora", "with-two-lame"]
brew "py2cairo"
brew "pygobject3"
brew "gst-python"
brew "hicolor-icon-theme"
brew "gtk+"
brew "gtk-doc"
brew "hashcat"
brew "heroku"
brew "highlight"
brew "hledger"
brew "html-xml-utils"
brew "htop-osx"
brew "httpie"
brew "hub"
brew "id3lib"
brew "iftop"
brew "imagemagick"
brew "imagesnap"
brew "intltool"
brew "ipcalc"
brew "itstool"
brew "jemalloc"
brew "jpeg-turbo"
brew "jpegoptim"
brew "oniguruma"
brew "jq"
brew "json-c"
brew "jsonpp"
brew "lastpass-cli"
brew "ledger"
brew "lesspipe"
brew "libidn"
brew "lftp"
brew "libass"
brew "libcaca"
brew "libebml"
brew "libevent"
brew "libid3tag"
brew "libmagic"
brew "libmatroska"
brew "memcached", restart_service: true
brew "libmemcached"
brew "libmpdclient"
brew "libpng@1.2"
brew "libpqxx"
brew "libsamplerate"
brew "libshout"
brew "libsodium"
brew "libssh2"
brew "libstfl"
brew "libtermkey"
brew "libuv"
brew "libvo-aacenc"
brew "libvterm"
brew "libxslt"
brew "little-cms2"
brew "lnav"
brew "lynx"
brew "mackup"
brew "mad"
brew "makedepend"
brew "makeicns"
brew "mas"
brew "mhash"
brew "mcrypt"
brew "md5sha1sum"
brew "mercurial"
brew "mitmproxy"
brew "mkvtoolnix"
brew "mobile-shell"
brew "moreutils"
brew "mozilla-addon-sdk"
brew "mp4v2"
brew "mpg123"
brew "mpv", args: ["with-bundle"]
brew "msgpack"
brew "msmtp"
brew "mtr"
brew "multitail"
brew "mycli"
brew "mysql"
brew "ncdu"
brew "taglib"
brew "ncmpcpp"
brew "ncurses"
brew "screenresolution"
brew "neofetch"
brew "netcat"
brew "newsbeuter"
brew "nmap"
brew "node"
brew "talloc"
brew "notmuch"
brew "numpy"
brew "offlineimap"
brew "sdl"
brew "sdl_net"
brew "open-tyrian"
brew "optipng"
brew "ossp-uuid"
brew "p7zip"
brew "pandoc"
brew "pgcli"
brew "phantomjs"
brew "pidof"
brew "plantuml"
brew "platformio"
brew "portaudio"
brew "portmidi"
brew "progress", args: ["HEAD"]
brew "pv"
brew "pwgen"
brew "pyenv"
brew "pygobject"
brew "pygtk"
brew "q"
brew "qt"
brew "qcachegrind"
brew "qemu"
brew "qt@5.5"
brew "ruby-build"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "rsync"
brew "rust"
brew "s-lang"
brew "screenfetch"
brew "sdl_image"
brew "sdl_mixer"
brew "sdl_ttf"
brew "selecta"
brew "shellcheck"
brew "siege"
brew "sip", args: ["with-python3"]
brew "slurm"
brew "socat"
brew "source-highlight"
brew "sox"
brew "speedtest_cli"
brew "ssh-copy-id"
brew "stormssh"
brew "subversion"
brew "ta-lib"
brew "teensy_loader_cli"
brew "texi2html"
brew "the_silver_searcher"
brew "thefuck"
brew "tidy-html5"
brew "tig"
brew "tmux"
brew "toilet"
brew "tokyo-cabinet"
brew "tomee-plus"
brew "trash"
brew "tree"
brew "tsung"
brew "two-lame"
brew "ucl"
brew "unibilium"
brew "unison"
brew "unixodbc"
brew "unrar"
brew "urlview"
brew "utf8proc"
brew "vifm"
brew "w3m"
brew "watch"
brew "wget"
brew "x265"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "eugenmayer/dockersync/unox"
brew "homebrew/apache/httpd24"
brew "homebrew/php/php56", args: ["with-httpd24", "with-thread-safety"]
brew "homebrew/php/boris"
brew "homebrew/php/composer"
brew "homebrew/php/igbinary"
brew "homebrew/php/php56-igbinary"
brew "homebrew/php/php56-intl"
brew "homebrew/php/php56-lzf"
brew "homebrew/php/php56-mcrypt"
brew "homebrew/php/php56-memcache"
brew "homebrew/php/php56-memcached"
brew "homebrew/php/php56-oauth"
brew "homebrew/php/php56-pthreads"
brew "homebrew/php/php56-twig"
brew "homebrew/php/php70", args: ["with-httpd24", "with-pear"]
brew "homebrew/php/php70-igbinary"
brew "homebrew/php/php70-imagick"
brew "homebrew/php/php70-intl"
brew "homebrew/php/php70-ioncubeloader"
brew "homebrew/php/php70-lzf"
brew "homebrew/php/php70-mcrypt"
brew "homebrew/php/php70-oauth"
brew "homebrew/php/php70-opcache"
brew "homebrew/php/php71", args: ["with-httpd24", "with-pear", "with-thread-safety"]
brew "homebrew/php/php71-igbinary"
brew "homebrew/php/php71-imagick"
brew "homebrew/php/php71-lzf"
brew "homebrew/php/php71-mcrypt"
brew "homebrew/php/php71-oauth"
brew "monochromegane/pt/pt"
brew "mopidy/mopidy/libspotify"
brew "mopidy/mopidy/python-backports-ssl-match-hostname"
brew "mopidy/mopidy/python-pycparser"
brew "mopidy/mopidy/python-pykka"
brew "neomutt/neomutt/neomutt"
brew "neovim/neovim/neovim", args: ["HEAD"]
brew "osx-cross/avr/avr-binutils"
brew "osx-cross/avr/avr-gcc"
brew "osx-cross/avr/avr-libc"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "arduino"
cask "betterzipql"
cask "bit-slicer"
cask "chicken"
cask "cord"
cask "cyberduck"
cask "dropbox"
cask "emacs"
cask "flightgear"
cask "fluid"
cask "flux"
cask "font-fira-code"
cask "google-chrome"
cask "google-drive"
cask "google-hangouts"
cask "gpgtools"
cask "handbrakecli"
cask "hex-fiend"
cask "imageoptim"
cask "integrity"
cask "jdownloader"
cask "keepingyouawake"
cask "keybase"
cask "kindlegen"
cask "libreoffice"
cask "macdown"
cask "macvim"
cask "mendeley-desktop"
cask "ngrok"
cask "openemu"
cask "paparazzi"
cask "pdfsam-basic"
cask "pgadmin3"
cask "postgres"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
cask "rdm"
cask "screenhero"
cask "sequel-pro"
cask "sourcetree"
cask "spotify"
cask "suspicious-package"
cask "sweet-home3d"
cask "teamspeak-client"
cask "techstoreclub-simple-comic"
cask "torbrowser"
cask "tuntap"
cask "tuxguitar"
cask "ubersicht"
cask "vagrant"
cask "virtualbox"
cask "vlc"
cask "wineskin-winery"
cask "wireshark"
cask "wwdc"
mas "Alternote", id: 974971992
mas "Caffeine", id: 411246225
mas "CloudApp", id: 417602904
mas "ForkLift", id: 412448059
mas "GarageBand", id: 408980954
mas "Helium", id: 1054607607
mas "iMovie", id: 408981434
mas "Key Codes", id: 414568915
mas "Keynote", id: 409183694
mas "Kuvva", id: 451557061
mas "LastPass", id: 926036361
mas "Monosnap", id: 540348655
mas "Numbers", id: 409203825
mas "Outbank", id: 1094255754
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "Skitch", id: 425955336
mas "Soulver", id: 413965349
mas "SwordSoft Layout", id: 438034858
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
mas "Tweetbot", id: 557168941
mas "Veertu", id: 1024069033
mas "Wunderlist", id: 410628904
mas "Xcode", id: 497799835
