#!/bin/bash

function relink() {
	if [[ -h "$1" ]]; then
		echo "Relinking $1"
		# Symbolic link? Then recreate.
		rm "$1"
		ln -sn "$2" "$1"
	elif [[ ! -e "$1" ]]; then
		echo "Linking $1"
		ln -sn "$2" "$1"
	else
		echo "$1 exists as a real file, skipping."
	fi
}

cd $HOME
relink .ackrc $HOME/.dotfiles/tools/ackrc.symlink
relink .bash_aliases $HOME/.dotfiles/bash/bash_aliases.symlink
relink .bash_completion.d $HOME/.dotfiles/bash/bash_completion.d.symlink
relink .bash_functions $HOME/.dotfiles/bash/bash_functions.symlink
relink .bash_logout $HOME/.dotfiles/bash/bash_logout.symlink
relink .bash_paths $HOME/.dotfiles/bash/bash_paths.symlink
relink .bash_prompt $HOME/.dotfiles/bash/bash_prompt.symlink
relink .bashrc $HOME/.dotfiles/bash/bashrc.symlink
relink bin $HOME/.dotfiles/bin
relink .emacs.d $HOME/.dotfiles/emacs.d.symlink
relink .gemrc $HOME/.dotfiles/ruby/gemrc.symlink
relink .gitconfig $HOME/.dotfiles/git/gitconfig.symlink
relink .gitignore $HOME/.dotfiles/git/gitignore.symlink
relink .gvimrc $HOME/.dotfiles/vim/gvimrc.symlink
relink .hgignore $HOME/.dotfiles/hg/hgignore.symlink
relink .hgrc $HOME/.dotfiles/hg/hgrc.symlink
relink .inputrc $HOME/.dotfiles/linux-configs/inputrc.symlink
relink .irbrc $HOME/.dotfiles/ruby/irbrc.symlink
relink .irssi $HOME/.dotfiles/irssi.symlink
relink .profile $HOME/.dotfiles/bash/profile.symlink
relink .railsrc $HOME/.dotfiles/ruby/railsrc.symlink
relink .screenrc $HOME/.dotfiles/linux-configs/screenrc.symlink
relink .ssh/authorized_keys $HOME/.dotfiles/ssh/authorized_keys
relink .ssh/id_rsa.pub $HOME/.dotfiles/ssh/id_rsa.pub
relink .tmux.conf $HOME/.dotfiles/tools/tmux.conf.symlink
relink .vim $HOME/.dotfiles/vim/vim.symlink
relink .vimrc $HOME/.dotfiles/vim/vimrc.symlink
relink .zshrc $HOME/.dotfiles/zsh/zshrc.symlink
