#!/bin/bash

eval `dbus-launch --sh-syntax --exit-with-session`
eval `ssh-agent`

$HOME/.Xmodmap

[ -z `pgrep urxvtd` ] && urxvtd -q -o -f

[ -z `pgrep nm-applet` ] && sudo nm-applet &
[ -z `pgrep bluetooth-apple` ] && bluetooth-applet &
[ -z `pgrep xscreensaver` ] && xscreensaver -no-splash &
dropboxd &
HOME=$HOME/.dropbox-2 dropboxd &
HOME=$HOME/.dropbox-3 dropboxd &

[ -z `pgrep irexec` ] && irexec &
[ -z `pgrep mpdscribble` ] && mpdscribble

awsetbg ~/.config/awesome/zenburn/zenburn-background.png

exec ck-launch-session dbus-launch awesome
