#!/bin/bash

eval `dbus-launch --sh-syntax --exit-with-session`
eval `ssh-agent`

#[ -z `pgrep xautolock` ] && xautolock -locker "i3lock -d" -nowlocker "i3lock -d" &
dropboxd &
HOME=$HOME/.dropbox-2 dropboxd &

awsetbg ~/Downloads/wallpaper-retina-macbookpro.png
setxkbmap de

xinput set-int-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 8 1
xinput set-int-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 8 2
xinput set-int-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Timeout" 8 200
xinput set-int-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Axes" 8 7 6 4 5
synclient TouchpadOff=1

#eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
# You probably need to do this too:
#export SSH_AUTH_SOCK
#export GPG_AGENT_INFO
#export GNOME_KEYRING_CONTROL
#export GNOME_KEYRING_PID
eval "`gnome-keyring-daemon`"
export GNOME_KEYRING_PID
export GNOME_KEYRING_SOCKET

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
sudo nm-applet  &

#xcompmgr &
#tilda &

xmodmap $HOME/.Xmodmap

exec ck-launch-session dbus-launch awesome
#exec ck-launch-session dbus-launch i3
