(defun kleinmann-switch-dictionary()
  (interactive)
  (let* ((dic ispell-current-dictionary)
         (change (if (string= dic "deutsch8") "english" "deutsch8")))
    (ispell-change-dictionary change)
    (message "Dictionary switched from %s to %s" dic change)
    ))
(defun kleinmann-build-ctags ()
  (interactive)
  (message "building project tags")
  (let ((default-directory (projectile-project-root)))
    (shell-command (concat "ctags -e -R --extra=+fq -f TAGS *"))
    (message "tags built successfully")))

(defadvice find-file (before make-directory-maybe (filename &optional wildcards) activate)
  "Create parent directory if not exists while visiting file."
  (unless (file-exists-p filename)
    (let ((dir (file-name-directory filename)))
      (unless (file-exists-p dir)
        (make-directory dir t)))))
