;; -*- coding: utf-8 -*-
(defun kleinmann-large-font ()
  (interactive)
  (set-frame-font "Inconsolata 24"))
(defun kleinmann-normal-font ()
  (interactive)
  (set-frame-font "Inconsolata 14"))
(defun kleinmann-small-font ()
  (interactive)
  (set-frame-font "Inconsolata 12"))
(defun kleinmann-switch-dictionary()
      (interactive)
      (let* ((dic ispell-current-dictionary)
    	 (change (if (string= dic "deutsch8") "english" "deutsch8")))
        (ispell-change-dictionary change)
        (message "Dictionary switched from %s to %s" dic change)
        ))
