;; -*- coding: utf-8 -*-
(setq ispell-program-name "aspell")
(setq ispell-extra-args '("--sug-mode=fast"))
(add-hook 'message-mode-hook '(lambda ()
                                (flyspell-mode +1)))
(add-hook 'text-mode-hook '(lambda ()
                             (flyspell-mode +1)))

(defun fd-switch-dictionary()
      (interactive)
      (let* ((dic ispell-current-dictionary)
    	 (change (if (string= dic "deutsch8") "english" "deutsch8")))
        (ispell-change-dictionary change)
        (message "Dictionary switched from %s to %s" dic change)
        ))
